language: python

# For now only build molreps branch
# branches:
#   only:
#     - molreps

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
    - python: 3.6

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -n molreps python=3.6 pytest pytest-cov openbabel -c openbabel
  - source activate molreps
  - conda list
  - pip install codecov

before_script:
  - python -V

script:
  - pip install -e .
  - py.test -v --cov=./

after_success:
  - codecov

notifications:
  email: false